%YAML:1.0

# Classifiers location
CascadeFile: "C:/dev/workspace/WICAB_SingFinding/opencv-haar-classifier-training-master/classifier_lbp/cascade.xml"     # full path to cascade classifier CascadeFile
SVMFile: "C:/dev/workspace/WICAB_SingFinding/x64/Release/exitModel.svm"                                                 # full path to SVM model 

# Cascade search window parameters. It can be changed, but it is a good idea to keep the same aspect ratio (w/h = 1.5)
minWinSize:
    width: 18
    height: 12
CascadeScaleFactor: 1.1    # scale factor for multiscale detection 

maxWinSizeFactor: 8.       #specify largest search window as a multiple of minWinSize

# HOG
HOG_winSize:               # DO NOT CHANGE: this parameter should be changed only if the SVM is trained with a different window size 
    width: 36
    height: 24

SVMThreshold: .85          # sets the SVM confidence threshold   

# Preprocessing
CroppingFactors:           # specify which section of the image to process. Cropping origin is (0,0) i.e. top left corner
    width: 1.0
    height: 0.66

ScaleFactor: 0.66          # specify rescaling factor for cropped frames (helps with detection of small objects)

Flip: 1                    # flip input frames  (used for portrait vs landscape videos)
Transpose: 1               # transpose input frames (used for portrait vs landscape videos)

# Debug options
ShowIntermediate: 0